#!/usr/bin/env python3
"""Utilities for maintaining WeeChat themes.

Provides:
- `validate`: verify theme structure and command parity
- `build-index`: regenerate themes/README.md from theme metadata
- `scaffold`: create a new theme folder from a base theme

The canonical option set is taken from a reference theme (default: gruvbox).
"""

from __future__ import annotations

import argparse
import json
import shutil
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable

ROOT = Path(__file__).resolve().parents[1]
DEFAULT_REFERENCE_THEME = "gruvbox"
REQUIRED_THEME_FILES = ("theme.json", "README.md", "commands.txt")

README_TEMPLATE = """<!-- AUTO-GENERATED by themes/tools/theme_tools.py build-index -->

# WeeChat Themes

Custom color themes for WeeChat, inspired by popular shell themes, site palettes,
and original designs.

> Do not edit this file manually. Rebuild it with
> `python3 themes/tools/theme_tools.py build-index`.

## Available Themes

| Theme | Source | Description |
|-------|--------|-------------|
{rows}

## How to Apply a Theme

Each theme folder contains:

- **theme.json** — machine-readable metadata for tooling
- **README.md** — color analysis, palette reference, and usage notes
- **commands.txt** — all `/set` commands to apply the theme

### Inside WeeChat (recommended)

The `theme_loader.py` script (auto-loaded from `scripts/`) provides a `/theme` command:

```
/theme list              — show available themes
/theme apply gruvbox     — apply the gruvbox theme
/theme current           — show which theme is active
/theme save mytheme      — save current colors as a new theme
/theme reset             — reset active theme (unset all themed options)
```

Once applied, the active theme is remembered and **auto-applied on every WeeChat startup**.

### Shell: apply.sh (FIFO pipe)

Use the included `apply.sh` script to send commands through WeeChat's FIFO pipe from outside:

```bash
# If WeeChat runs in Docker (container name: weechat)
./themes/apply.sh gruvbox --docker

# If WeeChat runs on the host
./themes/apply.sh gruvbox
```

### Theme Tooling

A small maintenance tool lives at [themes/tools/theme_tools.py](tools/theme_tools.py):

```bash
# Validate all themes against the canonical option list
python3 themes/tools/theme_tools.py validate

# Rebuild this index from theme.json metadata
python3 themes/tools/theme_tools.py build-index

# Print a plain command list for sharing/pasting without the plugin
python3 themes/tools/theme_tools.py print-commands gruvbox > gruvbox.apply.txt

# Scaffold a new theme from an existing base theme
python3 themes/tools/theme_tools.py scaffold mytheme \
  --description "My new theme" \
  --source-label "Original design" \
  --base gruvbox
```

### Alternative: Paste in WeeChat

You can also paste the commands manually. To strip the comments first:

```bash
grep -v '^\\s*#' themes/gruvbox/commands.txt | grep -v '^\\s*$'
```

Copy the output and paste it into WeeChat's input bar.

### Alternative: FIFO one-liner

If you prefer a one-liner without the script:

```bash
# Host
FIFO=$(ls /tmp/weechat_fifo_* 2>/dev/null | head -1) && \
    grep -v '^\\s*#' themes/gruvbox/commands.txt | grep -v '^\\s*$' | \
  while read cmd; do echo "* $cmd" > "$FIFO"; done

# Docker
FIFO=$(docker exec weechat sh -c 'ls /tmp/weechat_fifo_* 2>/dev/null | head -1') && \
    grep -v '^\\s*#' themes/gruvbox/commands.txt | grep -v '^\\s*$' | \
  while read cmd; do docker exec weechat sh -c "echo '* $cmd' > $FIFO"; done
```

### Reset to Defaults

To undo a theme, you can reset individual settings:

```
/unset weechat.color.*
/unset irc.color.*
/unset buflist.format.*
/unset fset.color.*
/save
```

## Adding a New Theme

1. Scaffold a new folder with `theme_tools.py scaffold`
2. Update `theme.json` with the final source/description metadata
3. Edit `README.md` with palette analysis and screenshots/notes
4. Tune `commands.txt`
5. Run `python3 themes/tools/theme_tools.py validate`
6. Rebuild this index with `python3 themes/tools/theme_tools.py build-index`
7. Commit and push
"""

README_STARTER = """# {display_name}

{description}

## Source

- **Source**: {source_label}{source_suffix}

## Palette Notes

Describe the palette, role mapping, and any intentional exceptions here.

## Design Notes

- Chat background:
- Bar backgrounds:
- Accent colors:
- Special choices:
"""


@dataclass
class ThemeMetadata:
    name: str
    display_name: str
    description: str
    source_label: str
    source_url: str | None = None

    @classmethod
    def from_path(cls, path: Path) -> "ThemeMetadata":
        data = json.loads(path.read_text(encoding="utf-8"))
        source = data.get("source") or {}
        return cls(
            name=data["name"],
            display_name=data.get("display_name") or data["name"],
            description=data["description"],
            source_label=source["label"],
            source_url=source.get("url"),
        )

    def source_markdown(self) -> str:
        if self.source_url:
            return f"[{self.source_label}]({self.source_url})"
        return self.source_label


def iter_theme_dirs() -> list[Path]:
    return sorted(
        path for path in ROOT.iterdir()
        if path.is_dir() and not path.name.startswith(".") and path.name != "tools"
    )


def parse_commands(commands_path: Path) -> tuple[list[str], list[str]]:
    if not commands_path.exists():
        return [], []

    option_names: list[str] = []
    errors: list[str] = []
    save_seen = False
    non_comment_lines: list[str] = []
    seen: set[str] = set()

    for lineno, raw_line in enumerate(commands_path.read_text(encoding="utf-8").splitlines(), 1):
        line = raw_line.strip()
        if not line or line.startswith("#"):
            continue
        non_comment_lines.append(line)
        if line == "/save":
            save_seen = True
            continue
        if not line.startswith("/set "):
            errors.append(f"{commands_path.name}:{lineno}: unsupported command: {line}")
            continue

        parts = line.split(None, 2)
        if len(parts) < 3:
            errors.append(f"{commands_path.name}:{lineno}: malformed /set line")
            continue
        option_name = parts[1]
        if option_name in seen:
            errors.append(f"{commands_path.name}:{lineno}: duplicate option: {option_name}")
        seen.add(option_name)
        option_names.append(option_name)

    if not save_seen:
        errors.append(f"{commands_path.name}: missing trailing /save")
    elif non_comment_lines and non_comment_lines[-1] != "/save":
        errors.append(f"{commands_path.name}: /save must be the last non-comment line")

    return option_names, errors


def get_canonical_options(reference_theme: str) -> list[str]:
    reference_path = ROOT / reference_theme / "commands.txt"
    if not reference_path.exists():
        raise SystemExit(f"Reference theme not found: {reference_path}")
    option_names, errors = parse_commands(reference_path)
    if errors:
        raise SystemExit("Reference theme is invalid:\n- " + "\n- ".join(errors))
    return option_names


def validate_theme(theme_dir: Path, canonical_options: list[str]) -> list[str]:
    errors: list[str] = []
    theme_name = theme_dir.name

    for filename in REQUIRED_THEME_FILES:
        if not (theme_dir / filename).exists():
            errors.append(f"missing {filename}")

    metadata_path = theme_dir / "theme.json"
    if metadata_path.exists():
        try:
            metadata = ThemeMetadata.from_path(metadata_path)
            if metadata.name != theme_name:
                errors.append(f"theme.json name '{metadata.name}' does not match directory '{theme_name}'")
        except (KeyError, json.JSONDecodeError) as exc:
            errors.append(f"invalid theme.json: {exc}")

    commands_path = theme_dir / "commands.txt"
    option_names, command_errors = parse_commands(commands_path)
    errors.extend(command_errors)

    if option_names:
        if option_names != canonical_options:
            missing = [name for name in canonical_options if name not in option_names]
            extra = [name for name in option_names if name not in canonical_options]
            if missing:
                errors.append(f"missing options ({len(missing)}): {', '.join(missing[:5])}" + (" ..." if len(missing) > 5 else ""))
            if extra:
                errors.append(f"extra options ({len(extra)}): {', '.join(extra[:5])}" + (" ..." if len(extra) > 5 else ""))
            if not missing and not extra:
                for index, (expected, actual) in enumerate(zip(canonical_options, option_names), 1):
                    if expected != actual:
                        errors.append(
                            f"option order differs at position {index}: expected {expected}, got {actual}"
                        )
                        break

    readme_path = theme_dir / "README.md"
    if readme_path.exists():
        lines = readme_path.read_text(encoding="utf-8").splitlines()
        if lines and not lines[0].strip().startswith("# "):
            errors.append("README.md should start with a level-1 heading")

    return errors


def build_index(output_path: Path) -> None:
    rows = []
    for theme_dir in iter_theme_dirs():
        metadata_path = theme_dir / "theme.json"
        if not metadata_path.exists():
            continue
        metadata = ThemeMetadata.from_path(metadata_path)
        rows.append(
            f"| [{metadata.name}]({metadata.name}/) | {metadata.source_markdown()} | {metadata.description} |"
        )
    output_path.write_text(README_TEMPLATE.format(rows="\n".join(rows)), encoding="utf-8")


def print_commands(args: argparse.Namespace) -> int:
    commands_path = ROOT / args.theme / "commands.txt"
    if not commands_path.exists():
        print(f"error: theme commands not found: {commands_path}", file=sys.stderr)
        return 1

    lines = []
    for raw_line in commands_path.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#"):
            continue
        if line == "/save" and not args.keep_save:
            continue
        lines.append(line)

    output = "\n".join(lines) + ("\n" if lines else "")
    if args.output:
        Path(args.output).write_text(output, encoding="utf-8")
    else:
        sys.stdout.write(output)
    return 0


def scaffold_theme(args: argparse.Namespace) -> int:
    theme_dir = ROOT / args.name
    if theme_dir.exists():
        print(f"error: theme directory already exists: {theme_dir}", file=sys.stderr)
        return 1

    base_dir = ROOT / args.base
    if not (base_dir / "commands.txt").exists():
        print(f"error: base theme not found: {base_dir}", file=sys.stderr)
        return 1

    display_name = args.display_name or args.name.replace("_", " ").title()
    theme_dir.mkdir(parents=True)

    metadata = {
        "name": args.name,
        "display_name": display_name,
        "description": args.description,
        "source": {
            "label": args.source_label,
            "url": args.source_url,
        },
    }
    (theme_dir / "theme.json").write_text(json.dumps(metadata, indent=2) + "\n", encoding="utf-8")

    source_suffix = f" ({args.source_url})" if args.source_url else ""
    (theme_dir / "README.md").write_text(
        README_STARTER.format(
            display_name=display_name,
            description=args.description,
            source_label=args.source_label,
            source_suffix=source_suffix,
        ),
        encoding="utf-8",
    )

    shutil.copyfile(base_dir / "commands.txt", theme_dir / "commands.txt")
    return 0


def run_validate(args: argparse.Namespace) -> int:
    canonical_options = get_canonical_options(args.reference)
    theme_names = args.themes or [path.name for path in iter_theme_dirs() if (path / "commands.txt").exists()]

    any_errors = False
    for theme_name in theme_names:
        theme_dir = ROOT / theme_name
        errors = validate_theme(theme_dir, canonical_options)
        if errors:
            any_errors = True
            print(f"[FAIL] {theme_name}")
            for error in errors:
                print(f"  - {error}")
        else:
            print(f"[ OK ] {theme_name}")

    if any_errors:
        print("\nValidation failed.", file=sys.stderr)
        return 1
    return 0


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    subparsers = parser.add_subparsers(dest="command", required=True)

    validate_parser = subparsers.add_parser("validate", help="validate theme files")
    validate_parser.add_argument("themes", nargs="*", help="theme names to validate")
    validate_parser.add_argument(
        "--reference",
        default=DEFAULT_REFERENCE_THEME,
        help=f"reference theme for canonical option order (default: {DEFAULT_REFERENCE_THEME})",
    )
    validate_parser.set_defaults(func=run_validate)

    build_index_parser = subparsers.add_parser("build-index", help="rebuild themes/README.md")
    build_index_parser.add_argument(
        "--output",
        default=str(ROOT / "README.md"),
        help="output README path",
    )
    build_index_parser.set_defaults(func=lambda args: build_index(Path(args.output)) or 0)

    print_commands_parser = subparsers.add_parser(
        "print-commands",
        help="emit plain /set commands for a theme",
    )
    print_commands_parser.add_argument("theme", help="theme name")
    print_commands_parser.add_argument(
        "--keep-save",
        action="store_true",
        help="include the trailing /save line",
    )
    print_commands_parser.add_argument(
        "--output",
        help="write commands to a file instead of stdout",
    )
    print_commands_parser.set_defaults(func=print_commands)

    scaffold_parser = subparsers.add_parser("scaffold", help="create a new theme folder")
    scaffold_parser.add_argument("name", help="new theme directory name")
    scaffold_parser.add_argument("--display-name", help="human-friendly theme name")
    scaffold_parser.add_argument("--description", required=True, help="short theme description")
    scaffold_parser.add_argument("--source-label", required=True, help="source label, e.g. Original design")
    scaffold_parser.add_argument("--source-url", help="source URL")
    scaffold_parser.add_argument(
        "--base",
        default=DEFAULT_REFERENCE_THEME,
        help=f"base theme to copy commands.txt from (default: {DEFAULT_REFERENCE_THEME})",
    )
    scaffold_parser.set_defaults(func=scaffold_theme)

    return parser


def main(argv: Iterable[str] | None = None) -> int:
    parser = build_parser()
    args = parser.parse_args(list(argv) if argv is not None else None)
    return args.func(args)


if __name__ == "__main__":
    raise SystemExit(main())
